version: '2.4'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - server

  server_a:
    image: websocket-app:latest
    container_name: server_a-app
    restart: on-failure:3
    ports:
      - "8080:8080"
    networks:
      - server
    cpus: 0.5
    mem_limit: 512m

  server_b:
    image: websocket-app:latest
    container_name: server_b-app
    restart: on-failure:3
    ports:
      - "8081:8080"
    networks:
      - server
    cpus: 0.5
    mem_limit: 512m

networks:
  server:
    driver: bridge