logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.web.socket.messaging: DEBUG

spring:
  data:
    redis:
#      host: localhost
      host: redis
      port: 6379