logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.web.socket.messaging: DEBUG

spring:
  data:
    redis:
      host: localhost
      port: 6379

---
spring:
  config:
    activate:
      on-profile: serverA
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: serverB
server:
  port: 8081